#Database configuration
spring:
  datasource:
    driver-class-name: ${Driver_Class}
    url: ${URL}
    username: ${USER}
    password: ${PASS}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      connection:
        useSSL: false
  application:
    name: EmployeeService   
    
wpb:
  hsbc:
    input:
      notification-type: CCM, mobile
      field1: treatment,operational
      field2: gps,obs 
      